### ISSUE TITLE
Capabilities & Config do not work as expected

### ISSUE THREAD

**Issue by dfsoeten** [crossbrowsertesting/selenium-codeception#2]
The WebDriver `browser` config option is responsible for changing the browser, the option `browserName` doesn't work at all. 

1. The `browser` option is responsible for changing the specified browser, not `browserName`.

**Config:** 
```
modules:
  config:
    WebDriver:
      browser: chrome
      capabilities:
        browserName: 'Firefox'
        version: 'latest'
        platform: 'Windows 10'
```
**Result:**
![image](https://user-images.githubusercontent.com/19746471/61298668-ed75a800-a7de-11e9-9707-1d6ee1650398.png)

2. Specifying a browser will only work when a numeric version is given when using a Non-webdriver browser.
```
modules:
  config:
    WebDriver:
      browser: 'Internet Explorer'
      capabilities:
        version: 'latest'
        platform: 'Windows 10'
```

**Result:**
```
There was 1 error:

---------
1) PagesCest: Home page rendered
 Test  tests/behavioral/site/PagesCest.php:homePageRendered
                                                                                                                                                                                                                                  
  [Facebook\WebDriver\Exception\WebDriverException] JSON decoding of remote response failed.
Error code: 4
The response: 'Invalid browser api_name. Latest browsers are only supported on desktops for: Chrome, Firefox, Opera'
  
                                                                                                                                                                                                                                  
#1  /var/www/html/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:303
#2  /var/www/html/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:144
#3  /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:260
#4  /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:235
#5  /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:75
Artifacts:

Png: /var/www/html/tests/_output/PagesCest.homePageRendered.chrome.fail.png
Html: /var/www/html/tests/_output/PagesCest.homePageRendered.chrome.fail.html

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```
Chaging the above to version 11, the test behaves as expected. 

3. When passing in a `browserName` when the `browser` option is empty, an error message is thrown with the message `'Capabilities must specify either a browserName or browser_api_name so we know what browser to launch.'`. 

**Config:**
```
modules:
  config:
    WebDriver:
      browser: ''
      capabilities:
        browserName: 'Internet Explorer'
        version: '11'
        platform: 'Windows 10'
```
**Result:**
```
There was 1 error:

---------
1) PagesCest: Home page rendered
 Test  tests/behavioral/site/PagesCest.php:homePageRendered
                                                                                                                                                                                                                                   
  [Facebook\WebDriver\Exception\WebDriverException] JSON decoding of remote response failed.
Error code: 4
The response: 'Capabilities must specify either a browserName or browser_api_name so we know what browser to launch.'
  
                                                                                                                                                                                                                                   
#1  /var/www/html/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:303
#2  /var/www/html/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:144
#3  /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:260
#4  /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:235
#5  /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:75
Artifacts:

Png: /var/www/html/tests/_output/PagesCest.homePageRendered.chrome.fail.png
Html: /var/www/html/tests/_output/PagesCest.homePageRendered.chrome.fail.html

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

Please either fix the documentation, or the serverside test runner.
